/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export to clipboard': '导出到剪贴板',
    'Export': '导出',
    'Import': '导入',
    ' Generation': '产生',
    'Generation': '产生',
    'Buy Amount': '购买数量',
    'Current Combo': '当前组合',
    'max': '最大',
    'Ores': '矿石',
    'School': '学校',
    'store': '商店',
    'Newbie Miner': '菜鸟矿工',
    'Farm': '农场',
    'ore per second.': '矿石每秒。',
    'ores per second.': '矿石每秒。',
    'Quarry': '采石场',
    'research': '研究',
    'New!': '新!',
    'COLLECT': '收集',
    'Available Upgrades': '可用升级',
    'Break 10 rocks': '打破10岩石',
    '': '',
    'Quest Board': '任务板',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'In ore name we pray, amen.': '我们祈祷，阿门。',
    'Research Power': '研究力量',
    'Diggy diggy hole.': '挖洞，挖洞。',
    'Praise to ye Old Ore Gods.': '赞美你们古老的矿石神。',
    'Rock pun here': '岩石双关语在这里',
    'Research Power Up': '研究力量提升',
    'Requires': '需要',
    'Reach a 5 hit combo': '达到5点连击',
    'Combo Baby': '组合宝贝',
    'Fetch quests are the greatest aren\'t they?': '获取任务是最棒的不是吗?',
    'ores per second while researching.': '研究时的每秒矿石量。',
    'Onwards to adventure! Go on quests to find greater rewards and even mysterious artifacts!': '开始冒险吧!继续寻找更大的奖励，甚至是神秘的文物!',
    'Fragility Spectacles': '易碎眼镜',
    'I can see... I can FIGHT!': '我能看到……我能战斗!',
    'As you can tell, these are pretty lame... Submit your own to /u/name_is_Syn': '正如你所看到的，这些很差劲……提交你自己的到/u/name_is_Syn',
    'Allows you to spot "weak spots" within the ore. Hitting the weak spot generates 5x the normal amount.': '让你发现矿石的“弱点”。击中弱点会产生5倍于正常数量的能量。',
    ' research': '研究',
    'Research Power': '研究力量',
    'The poop helps the ore mature.': '粪便有助于矿石的成熟。',
    'Novice Miner': '新手矿工',
    'What is a rocks favorite fruit? ... Pom-a-granite': '岩石最喜欢的水果是什么?…花岗岩',
    'Manure Spreader': '撒肥机',
    'These puns sure are all ore nothing': '这些双关语毫无意义',
    'There are a few gems amongst all these terrible rock puns': '在所有这些可怕的岩石双关语中有一些宝石',
    'Rocks really rock!': '岩石真摇滚!',
    'I can\'t believe I\'m googling rock puns right now': '真不敢相信我现在在谷歌上搜索摇滚双关语',
    'Farms are currently generating': '农场目前正在生产',
    'Farm is generating': '农场正在生产',
    'Each Farm generates': '每个农场生成',
    'Don\'t take life for granite': '不要为花岗岩而死',
    'Composition Notebooks': '作文笔记本',
    'What happens when you throw a blue rock in the red sea? ... It gets wet': '如果你把一块蓝石扔进红海会发生什么?…它会湿',
    '[ School Production Multiplier': '[学校生产倍数',
    '[ Farm Production Multiplier': '[农场生产倍数',
    'This totally makes sense...': '这完全有道理…',
    'Teach students about the wonders of ore.': '教学生关于矿石的神奇之处。',
    'Schools are generating': '学校正在产生',
    'Schools are currently generating': '学校目前正在产生',
    'School is generating': '学校正在产生',
    'of your total OpS': '你的全部行动',
    'Jesus christ Marie, they\'re minerals!': '上帝啊，它们是矿物质!',
    'Increases the production multiplier of Schools by 1': '使学校的生产倍数增加1',
    'Increases the production multiplier of Farms by 1': '使农场的生产倍数增加1',
    'Increases the production multiplier of Quarries by 1': '使采石场的生产倍数增加1',
    'Cultivate the lands for higher quality ores.': '耕种土地以获得更高质量的矿石。',
    'Each School generates': '每个学校产生',
    'College ruled!': '大学说了算!',
    'Break your first rock': '打破你的第一块石头',
    'All rock and no clay makes you a dull boy (or girl': '只有石头没有泥土，会使你成为一个迟钝的男孩(或女孩',
    'Did you see that cleavage? Now that\'s some gneiss schist.': '你看到分裂了吗？ 现在，这是一些片麻岩片岩。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Power Needed: ": "力量需求: ",
    "Refined Ores: ": "提炼矿石: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " Thousand": " 千",
    " hit combo": " 点击组合",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);