/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export to clipboard': '导出到剪贴板',
    'Export': '导出',
    'Import': '导入',
    ' Generation': ' 世代',
    'Generation': '世代',
    'Buy Amount': '购买数量',
    'Current Combo': '当前连击',
    'max': '最大',
    'Ores': '矿石',
    'School': '学校',
    'store': '商店',
    'Newbie Miner': '菜鸟矿工',
    'Farm': '农场',
    'ore per second.': '矿石每秒。',
    'ores per second.': '矿石每秒。',
    'Quarry': '采石场',
    'research': '研究',
    'New!': '新!',
    'COLLECT': '收集',
    'Available Upgrades': '可用升级',
    'Break 10 rocks': '打破10岩石',
    '[ Quarry Production Multiplier': '[ 采石场产量乘数',
    'Quest Board': '任务板',
    "Available points": "可用点数",
    "Church": "教堂",
    "Copper Coating": "镀铜",
    "Crypt": "墓穴",
    "EXPORT": "导出",
    "Factory": "工厂",
    "Farms": "农场",
    "Loading...": "加载中...",
    "OK": "确定",
    "ores educated.": "受过教育的矿石。",
    "ores harvested.": "收获的矿石。",
    "Save Game": "保存游戏",
    "Solo": "单人",
    "Schools": "学校",
    "Save Loaded Successfully": "存档加载成功",
    "The rock reminisced about ages past and felt sedimental": "这块岩石让人想起过去的岁月，感觉像是沉积物",
    "Unfortunately, the device you are playing on has a screen too small for More Ore.": "不幸的是，您正在玩的设备的屏幕对于 本游戏 来说太小了。",
    "View Changelog": "查看更新日志",
    "Wipe Save": "删除存档",
    "WIPE": "删档",
    "You can": "你可以",
    "your save": "你的存档",
    "your save and reach out to the developer on": "您的存档并与开发人员联系",
    "Hospital": "医院",
    "If the game doesn't load, your save might be corrupted.": "如果游戏无法加载，则您的保存可能已损坏。",
    "Join Our Discord": "加入我们的Discord",
    "Monolith": "巨石",
    "What is a rocks favorite lullaby? Rock-A-Bye baby.": "石头最喜欢的摇篮曲是什么？ 摇滚再见宝贝。",
    "\"weak spots\"": "\"弱点\"",
    "/sec": "/秒",
    "Allows you to spot": "让你一眼就看出来",
    "Announcement: To test the quality of your pickaxe, try whacking yourself with it a couple times.": "公告：要测试您的镐的质量，请尝试用它敲打自己几次。",
    "Available Research": "可用研究",
    "[ INSERT ROCK PUN HERE ]": "[在此处插入摇滚双关语]",
    "ACHIEVEMENT UNLOCKED": "成就解锁",
    "Created by Syns Studio": "作者是 Syns Studio",
    "Designated mining area.": "指定矿区。",
    "for every building you own.": "对于您拥有的每一栋建筑。",
    "Game Saved": "游戏已保存",
    "Hitting the weak spot generates": "击中弱点产生",
    "How do you put a rock baby to sleep? You rock it.": "你如何让石头婴儿入睡？ 你摇摇它就可以。",
    "Increase": "提高",
    "Increase base production of": "提高基础产量",
    "or": "或",
    "Permanently increase": "永久增加",
    "So what are you serving time for? Granite theft auto, you? Basalt and battery.": "那么你服务的时间是什么？ 花岗岩盗窃自动，你呢？ 玄武岩和电池。",
    "Thank you so much for playing my game!": "非常感谢你玩我的游戏！",
    "the normal amount.": "正常数量。",
    "Using": "使用",
    "What is a rocks favorite compliment? You rock!": "石头最喜欢的赞美是什么？ 你摇滚！",
    "within the ore.": "矿石之中。",
    "by": " ",
    "Gold Coating": "镀金",
    "OpC": "每次点击得到的矿石",
    "ago on": "以前",
    "Bork bork.": "博克博克。",
    "Caps out at": "上限在",
    "Enables offline gain": "启用离线增益",
    "ferocious animal": "凶猛动物",
    "Increase maximum": "提高最大值",
    "Increase the": "提高",
    "normal speed.": "正常的速度。",
    "of your": "关于你的",
    "Offline gain is": "离线增益",
    "Owned Research": "拥有的研究",
    "research power": "研究力量",
    "size": "尺寸",
    "This": "这",
    "Unlocked": "已解锁",
    "Watchdog": "看门狗",
    "watches over your buildings and makes sure they don't slack!": "监视您的建筑物并确保它们不会松懈！",
    "weak spot": "弱点",
    "[ Church Production Multiplier": "[教堂生产乘数",
    "Combo Loss": "连击损失",
    "Each Quarry generates": "每个采石场产生",
    "Floodlights": "射灯",
    "ores mined.": "开采的矿石。",
    "Quarries": "采石场",
    "Some of these jokes might flourite over your head...": "其中一些笑话可能会在你的脑海中浮现......",
    "Staring into one of them is like starting into a billion suns.": "凝视其中一个就像开始进入十亿个太阳。",
    "weak spot multiplier": "弱点倍增器",
    "A research is already in progress": "一项研究已经在进行中",
    "after use.": "使用后。",
    "Combo Shield": "连击护盾",
    "Iron Coating": "镀铁",
    "Prevents an accidental click on the ore when on a combo. Becomes available again": "防止在连击时意外点击矿石。 再次可用",
    "Confucious once said: \"Don't forget to make backups!\"": "孔子曾经说过：“不要忘记备份！”",
    "Not enough ores": "没有足够的矿石",
    "Intermediate Miner": "中级矿工",
    "Stats": "统计",
    "Strike the Earth": "冲击地球",
    "That Tickled": "那个挠痒痒的",
    "Times Refined": "时代精进",
    "Total Ores Earned": "获得的矿石总量",
    "Total time": "总时间",
    "Volume": "音量",
    "Weak Spot Clicks": "弱点点击",
    "Weekly": "每周",
    "What do you call an Irish gem thats fake? A sham rock.": "你怎么称呼爱尔兰宝石是假的？ 一块假石头。",
    "What does a rock and prison have in common? They both did hard time.": "岩石和监狱有什么共同点？ 他们俩都过得很辛苦。",
    "Yearly": "每年",
    "You don't have this unlocked": "你还没有解锁这个",
    "[achievement]": "[成就]",
    "[building achievement]": "[建筑成就]",
    "[combo achievement]": "[连击成就]",
    "[generation achievement]": "[世代成就]",
    "[LOCKED]": "[未解锁]",
    "[opc achievement]": "[矿石每次点击成就]",
    "[ops achievement]": "[矿石每秒成就]",
    "Achievements": "成就",
    "Advanced Miner": "高级矿工",
    "bar": "条形",
    "bar+number": "条形+数字",
    "Can you pass me the basalt and bapepper?": "你能把玄武岩和 黑胡椒 递给我吗？",
    "Copy this to your clipboard!": "将此复制到您的剪贴板！",
    "default": "默认",
    "Debug - Careful here!": "调试 - 这里要小心！",
    "Export Save": "导出存档",
    "export save": "导出存档",
    "Exalted Miner": "尊贵的矿工",
    "Educated": "博学",
    "first": "第一",
    "General": "常规",
    "God Miner": "优秀矿工",
    "Hide Ore Particles": "隐藏矿石粒子",
    "Hide Rising Text": "隐藏上升文本",
    "Highest Combo": "最高连击",
    "I Felt That": "我觉得",
    "import save": "导入保存",
    "Master Miner": "矿工大师",
    "Mine your first ore": "开采你的第一个矿石",
    "Miscellaneous": "杂项",
    "Missing research power up": "缺少研究能力",
    "Mute SFXs": "静音 SFX",
    "New": "新",
    "none": "无",
    "number": "数字",
    "Number Format": "数字格式",
    "Ok": "确定",
    "Ore Clicks": "矿石点击",
    "Ore HP Type": "矿石HP类型",
    "Ore Store": "矿石商店",
    "Ore-aid Stand": "助矿台",
    "Ores Earned": "获得的矿石",
    "percentage": "百分比",
    "Performance": "表现",
    "Preferences": "喜好",
    "Refinee": "精炼者",
    "Refiner": "精炼机",
    "Retirement Plan": "退休计划",
    "rock.": "岩石。",
    "Rocks Destroyed": "摧毁的石头",
    "rocks.": "岩石。",
    "Saves": "保存",
    "scientific-notation": "科学计数法",
    "Settings": "设置",
    "bar+percentage": "条形+百分比",
    "Cancel": "取消",
    "click above to copy to your clipboard": "单击上方以复制到剪贴板",
    "Import Save": "导入存档",
    "Paste Your Save Here": "在此处粘贴您的保存",
    "Show Animated Bg": "显示动画背景",
    "Show FPS": "显示 FPS",
    "The ingot were gossiping about the ore: They're so unrefined!": "铁锭在议论矿石：它们太不精炼了！",
    "[ Factory Production Multiplier": "[ 工厂生产乘数",
    "Assembly line this SH%* up!": "组装线这个 SH%* 提升！",
    "Churches": "教堂",
    "Each Church generates": "每个教堂生产",
    "Join our discord and add your name into the game!": "加入我们的 discord，将您的名字添加到游戏中！",
    "Manufacture your ores.": "制造你的矿石。",
    "OpS": "矿石每秒",
    "ores enlightened.": "矿石开悟了。",
    "Read the words of our l-ore-d and savior.": "阅读我们的 l-ore-d 和救世主的话。",
    "Scripture Reading": "经文阅读",
    "are generating": "正在生成",
    "Did you know rock was magma before it was cool?": "你知道岩石在冷却之前是岩浆吗？",
    "Doggybag": "打包袋",
    "Increases maximum amount of ores gained while away to": "增加离开时获得的最大矿石量",
    "item while away.": "物品当离开时。",
    "Lowers offline production penalty from": "降低离线生产惩罚",
    "makes it ever more menacing.": "让它变得更具威胁性。",
    "Ore Storage": "矿石储存",
    "Spiked Collar": "有刺项圈",
    "This little accessory for your": "这个小配件适合你",
    "to": "到",
    "watchdog": "看门狗",
    "What's a rocks favorite kind of music? Rock music.": "石头最喜欢的音乐是什么？ 摇滚（Rock）音乐。",
    "Your doggo will now store up to": "您的 打包袋 现在最多可存储",
    "As you can tell, these are pretty lame... Submit your own in our Discord!": "如您所知，这些非常蹩脚……在我们的 Discord 中提交您自己的！",
    "Destroyed": "摧毁",
    "Gained": "获得",
    "Hmmm... I wonder what happens if I click on the left torch 20 times...": "嗯...我想知道如果我点击左边的火炬 20 次会发生什么...",
    "ores.": "矿石.",
    "RECAP": "回顾",
    "Welcome Back": "欢迎回来",
    "You want to escape the rock puns? Too slate!": "你想逃离石头双关语吗？ 太片面了！",
    "You were gone for": "你离开了",
    "[ level": "[ 等级",
    "Common Pickaxe": "普通镐",
    "Currently Equipped": "当前已装备",
    "Damage": "伤害",
    "Epic Pickaxe": "史诗镐",
    "Equip": "装备",
    "Gold Pickaxe": "金镐",
    "if the building amount owned is a multiple of": "如果拥有的建筑数量是",
    "Increase building production by": "增加建筑产量",
    "New Item -": "新物品 -",
    "OCD": "OCD",
    "overall ore gain": "总矿石收益",
    "Platinum Coating": "铂金涂层",
    "Polished Nuggy": "抛光块",
    "Shitty Wood Pickaxe": "烂木镐",
    "Trash": "垃圾",
    "What's a rocks favorite band? Rolling Stones. I'll leave now.": "什么是摇滚最喜欢的乐队？ 滚石乐队。 我现在就走。",
    "Combo Pleb": "连击共享",
    "Not Even A Scratch": "连划痕都没有",
    "Agility": "敏捷",
    "Armor": "护甲",
    "Attack": "攻击",
    "BOSS APPROACHING...": "Boss正在接近...",
    "Crypt Lv.": "墓穴等级",
    "Dexterity": "灵巧",
    "Equips": "装备",
    "ERR NO.42069 - No rocks found": "ERR NO.42069 - 没有发现岩石",
    "Factory Lv.": "工厂等级",
    "Hospital Lv.": "医院等级",
    "Hp": "生命值",
    "Level Up": "升级",
    "Luck": "运气",
    "Lv.": "等级",
    "Monolith Lv.": "巨石等级。",
    "Skills": "技能",
    "Speed": "速度",
    "Strength": "力量",
    "O.A.R.D.I.S.": "O.A.R.D.I.S.",
    "[hero achievement]": "[英雄成就]",
    "[land achievement]": "[土地成就]",
    "[research achievement]": "[研究成果]",
    "[wtf achievement]": "[wtf成就]",
    "and combos don't count": "并且连击不算数",
    "Artifact Bag": "神器包",
    "Break me!": "不要点我！",
    "Can you smell what hes cooking": "你能闻到他在煮什么吗",
    "Cheater Detected": "检测到作弊者",
    "Combo Blessing Bonus": "组合祝福奖励",
    "Combo Preventor": "连击防护",
    "Dexterity I": "灵巧 I",
    "Extended Family": "大家庭",
    "Family Tree": "家谱",
    "Follow Syns Studio on Twitter": "在 Twitter 上关注 Syns Studio",
    "How can she slap": "她怎么能打",
    "Relatives": "亲戚们",
    "Sky Castle": "天空城堡",
    "sponsors :": "赞助商：",
    "Stone Hut": "石屋",
    "Student Researcher": "学生研究员",
    "Sussy Rock": "苏西摇滚",
    "Teehee I Lied": "Teehee 我说谎了",
    "Time in Game": "游戏时间",
    "UFO": "飞碟",
    "Visit r/moreore": "访问 r/moreore",
    "Wishlist More Ore on Steam": "Steam 上的 无尽的挖矿",
    "You can hold down your mouse to click!": "你可以按住鼠标点击！",
    "your save and reach out to the developer\n                on": "保存并联系开发者在\n",
    "Oreverse": "逆向",
    "Join the Discord": "加入 Discord",
    "Ore Treasury Bonus": "矿石宝库奖励",
    "OpS and OpC is reduced by": "OpS 和 OpC 减少了",
    "[ Stone Hut Production Multiplier": "[石屋生产乘数",
    "And more as you unlock new things ;": "当你解锁新事物时还有更多；",
    "Heck yea! 😘": "哎呀！ 😘",
    "Hire the homo-erectus for cheap manual labor": "雇用直立人以获得廉价的体力劳动",
    "If nothing happens, you might have an adblocker on. Turn it off, refresh and try again": "如果没有任何反应，您可能打开了广告拦截器。 关闭它，刷新并重试",
    "Nah": "不了",
    "once it's over!": "一旦结束！",
    "Oonga-boonga!": "呜呜呜！",
    "Potential Rewards": "潜在回报",
    "Power to the pebble": "卵石的力量",
    "random reward": "随机奖励",
    "Support the Dev": "支持开发",
    "This is a great way to show your love and support to me! The dev 😊❤️": "这是表达您对我的爱和支持的好方法！ 开发者😊❤️",
    "v. 1.5.9 Beta": "v. 1.5.9 测试版",
    "Watch a 10 second video and get a": "观看 10 秒视频并获得",
    "[ Upgrade ]": "[ 升级 ]",
    "Break": "打破",
    "Break your": "打破你的",
    "Buy buildings for passive income": "购买建筑物以获得被动收入",
    "Can't blow this house down.": "不能炸毁这房子。",
    "Combo Knight": "组合骑士",
    "Combo Master": "组合大师",
    "Combo Squire": "组合乡绅",
    "Each Stone Hut generates": "每个石屋都会生成",
    "Geology rocks, but Geography is where it's at.": "地质岩石，但地理是它的所在。",
    "Got some thoughts or concerns? Join the discord and post a message for the dev to see!": "有什么想法或顾虑吗？ 加入 discord 并发布消息以供开发人员查看！",
    "Hehe Funny Number I": "呵呵 搞笑数一",
    "I really lava you.": "我真的很喜欢你。",
    "IN TOTAL": "总共",
    "Keep purchasing buildings to increase your passive": "继续购买建筑来增加你的被动",
    "Looking at you Dylan.": "看着你，迪伦。",
    "Mine": "矿",
    "Misclick": "误点击",
    "more to unlock": "更多解锁",
    "OpS(Ores per Second": "OpS（每秒矿石",
    "ores": "矿石",
    "ores gathered.": "矿石聚集。",
    "Reach": "达到",
    "Refinest": "精炼",
    "RESEARCH": "研究",
    "save game": "保存游戏",
    "Show Boss Encounter Animation": "展示Boss遭遇动画",
    "Show Reward Ads": "显示奖励广告",
    "is generating": "正在生成",
    "Upgrade I": "升级 I",
    "Stone Huts": "石屋",
    "Stone Huts are currently generating": "石屋目前正在生成",
    "Stone Huts are generating": "石屋正在生成",
    "to unlock something special.": "解锁一些特别的东西。",
    "total ores mined": "开采的矿石总量",
    "v1.5.9 Beta": "v1.5.9 测试版",
    "while picking up new items.": "在拿起新物品时。",
    "wipe save": "擦除保存",
    "Pet Rocks": "宠物岩石",
    "Philantropist": "慈善家",
    "Pokemon Trainer": "口袋妖怪训练师",
    "Pooped": "拉屎",
    "Prescription Glasses": "处方眼镜",
    "Promoter": "发起人",
    "Rabbits Foot": "兔脚",
    "Roses": "玫瑰",
    "Rumpelstiltskin": "矮胖子皮",
    "Slum Lord": "贫民窟领主",
    "Subscriber": "订户",
    "Supporter": "支持者",
    "T1 T1 T1": "T1 T1 T1",
    "The Gangs All Here": "帮派都在这里",
    "Thornmail": "荆棘甲",
    "Travelled": "旅行",
    "Tulips": "郁金香",
    "Tweet Tweet": "鸣叫 鸣叫",
    "UFO I": "UFO I",
    "UFO II": "UFO II",
    "UFO III": "UFO III",
    "UFO IV": "UFO IV",
    "UFO V": "UFO V",
    "Wow a bat": "哇一只蝙蝠",
    "You've got to commit to geology... it's all ore nothing": "你必须致力于地质学......这一切都不是矿石",
    "[gold nugget achievement]": "[金块成就]",
    "[item achievement]": "[物品成就]",
    "[misc achievement]": "[杂项成就]",
    "[pet achievement]": "【宠物成就】",
    "Altruist": "利他主义者",
    "Backer": "支持者",
    "Beamed": "横梁",
    "Bi-Centennial": "双百年纪念",
    "Blind as a Bat": "像蝙蝠一样盲目",
    "Chonky Boi": "矮胖的博伊",
    "Combo Exodus": "组合出埃及记",
    "Combo God": "组合神",
    "Combo Jackpot": "组合大奖",
    "Combo King": "组合王",
    "Combo L337": "组合 L337",
    "Combo Saitama": "组合埼玉",
    "Combo Saiyan": "组合赛亚人",
    "Crypt III": "墓穴 III",
    "Daisies": "雏菊",
    "Disco Discord": "Disco Discord",
    "Egg III": "宠物蛋 III",
    "Egg IV": "宠物蛋 IV",
    "Egg V": "宠物蛋 V",
    "Exuded": "渗出",
    "Factory Mastery I": "工厂精通 I",
    "Galaxy Lord": "银河领主",
    "Getting Steamy": "变得热气腾腾",
    "Global Lord": "全球领主",
    "Gold Finger": "金手指",
    "Gold Rushing": "淘金",
    "Good Pet": "好宠物",
    "Good Samaritan": "好撒玛利亚人",
    "Hidden in Plain Sight": "隐藏在众目睽睽之下",
    "Luck V": "幸运五",
    "Mastery IV": "精通IV",
    "Miss a gold nugget.": "错过金块。",
    "Nice Guy": "好人",
    "Not a Neckbeard": "不是颈须",
    "Ooo Shiny": "哦闪亮",
    "[ Research Upgrade ]": "[ 研究升级 ]",
    "Clicking this doesn't give an achievement": "点击这个不会获得成就",
    "I liked carbon before it was coal.": "在它是煤之前，我喜欢碳。",
    "REQUIRES": "要求",
    "Start on your first research": "开始你的第一次研究",
    "[ Research Upgrade ] [ Repeatable ]": "[研究升级] [可重复]",
    "Can you pass me the basalt and pepper?": "你能把玄武岩和胡椒递给我吗？",
    "How does a rock make his name stand out... it makes it big and boulder": "一块岩石如何让他的名字脱颖而出......它使它变得又大又巨",
    "Silver Pickaxe": "银镐",
    "What's squidwards favorite painting? Boulder and Brash.": "章鱼哥最喜欢的画是什么？ 博尔德和布拉什。",
    "Remove Ads!": "移除广告！",
    "Gain Rewards without Ads": "无需广告即可获得奖励",
    "If nothing happens, you might have an adblocker on. Turn it off, refresh and try again!": "如果没有任何反应，您可能打开了广告拦截器。 关闭它，刷新并重试！",
    ", all ads will be removed from the game!": "，所有广告将从游戏中删除！",
    "even MORE": "even MORE",
    "Even More Support": "更多支持",
    "For just a": "只为了一个",
    "Got me blushin...": "Got me blushin...",
    "one-time": "一次性",
    "payment of": "支付",
    "Yessir": "是的先生",
    "You can also re-enable ads if ya like :": "如果您喜欢，您还可以重新启用广告：",
    "You want to support me": "你想支持我",
    "Did you hear about the crazy geologist? He finally hit rock bottom.": "你听说那个疯狂的地质学家了吗？他终于触底了。",
    "Let's rock and roll!": "让我们摇滚吧！",
    "This pun is short albite funny.": "这个双关语短小精悍有趣。",
    "Show Changelog": "显示更新日志",
    "MORE ORE is now on Steam! Click here to wishlist the game!": "More Ore 现在已登陆 Steam！ 单击此处将游戏列入愿望清单！",
    "It's been": "距离上次更新已经过去了 ",
    "days since the last update!": " 天！",
    "is currently in its beta stage. Saves aren't always stable and may require wipes. Feel free to drop by the": "目前处于测试阶段。 保存系统并不总是稳定的，可能需要擦拭。 欢迎随时来",
    "Next big update will hopefully be out on": "下一个重大更新有望推出",
    "PETS": "宠物",
    "Changelog": "更新日志",
    "Game Background Type": "游戏背景类型",
    "Research tab is now unlocked!": "研究标签现在已解锁！",
    "Achievements Won": "获得的成就",
    "Chief Miner": "首席矿工",
    "Click here to join my Patreon and gain access to secret Patron-only posts plus many other benefits!": "单击此处加入我的 Patreon 并访问仅限 Patron 的秘密帖子以及许多其他好处！",
    "gold nuggets": "金块",
    "Hands off me lucky charms. Increases the chance of": "把幸运符递给我。 增加几率去获得",
    "I'm not that tuff, but i'm a gneiss guy!": "我不是那种凝灰岩，但我是一个片麻岩人！",
    "Last week, my professor started talking about his favorite chalk. It was so dull.": "上周，我的教授开始谈论他最喜欢的粉笔。 太沉闷了。",
    "Leprechaun": "小妖精",
    "Upgrades": "升级",
    "Upgrades Owned": "拥有的升级",
    "Why are geologists great dates? They can make your bedrock.": "为什么地质学家是伟大的约会对象？ 他们可以成为你的基石。",
    ". Becomes available again": ". 再次变得可用",
    "Combo Preventer": "组合防止器",
    "Prevents an accidental click on the ore when on a combo.": "防止在组合中意外点击矿石。",
    "Special gold nugget effects automatically turns this on.": "特殊金块效果会自动启用此选项。",
    "Triggering the Combo Shield will automatically turn on Combo Preventer": "触发组合屏蔽将自动打开组合防止器",
    "Unlock a toggle that lets you freely mine without losing your current combo while active. Weak spots won't be clickable while this is active.": "解锁一个开关，让您在活动时自由挖掘，而不会丢失当前组合。当它处于活动状态时，弱点将无法点击。",
    "SOON ;": "很快 ;",
    "to submit bug reports and feature requests! Or just chat :": "去提交错误报告和功能请求！或者只是聊天：",
    "Pets": "宠物",
    "Hero": "英雄",
    "\"Can I borrow a sheet?\"": "“我可以借一张床单吗？”",
    "[ Crypt Production Multiplier": "[墓穴生产乘数",
    "[ Hospital Production Multiplier": "[ 医院生产乘数",
    "[ Sky Castle Production Multiplier": "[ 天空城堡生产乘数",
    "3 Ring Binder": "3环活页夹",
    "Adventure": "冒险",
    "An apple a day keeps the ore cancer away.": "每天一个苹果，远离矿石癌。",
    "ARM": "手臂",
    "Auto Pickaxe Pickup Settings": "自动镐拾取设置",
    "Bandage": "绷带",
    "Be the Lord of the Rings with our new 2.5\" binder!": "使用我们新的 2.5\" 活页夹成为指环王！",
    "bonus on all ore gain.": "所有矿石收益的加成。",
    "Cardboard Accessory": "纸板配件",
    "Communion": "圣餐",
    "Crypt x10": "墓穴 x10",
    "Crypts": "墓穴",
    "Crypts are currently generating": "墓穴目前正在生成",
    "Crypts are generating": "墓穴正在生成",
    "Deal more than 1,000 damage from a hit.": "击中造成超过 1,000 点伤害。",
    "Diamond Coating": "金刚石涂层",
    "Didnt Even Hurt": "甚至没有受伤",
    "Dig up graves faster": "更快地挖掘坟墓",
    "Each Crypt generates": "每个 墓穴 产生",
    "Each Factory generates": "每个工厂产生",
    "Each Hospital generates": "每个医院 产生",
    "Factories": "工厂",
    "Factories are generating": "工厂正在生产",
    "Factorys are currently generating": "工厂目前正在生产",
    "Floppy Squiggle Tubes": "软盘曲线管",
    "Generation 16": "第 16 代",
    "Groupwork": "团队合作",
    "Heal the poor ol damaged ores.": "治疗可怜的 ol 损坏的矿石。",
    "Hero Status": "英雄状态",
    "Hospital x10": "医院 x10",
    "Hospitals": "医院",
    "Hospitals are currently generating": "医院目前正在生成",
    "Hospitals are generating": "医院正在产生",
    "If I could tell you what these were for you'd buy twice as many.": "如果我能告诉你这些是给你的，你会买两倍的。",
    "Im in me mums tractor.": "我在我妈妈拖拉机。",
    "levels on refine.": "精炼等级。",
    "Looseleaf": "活页夹",
    "Monthly": "月刊",
    "More like W-ore-ship... haha...": "更像是矿船……哈哈……",
    "Note: Not communism.": "注意：不是共产主义。",
    "Obscenely obsessive compulsive disorder": "猥亵强迫症",
    "Obsessively obscene obsessive compulsive disorder": "痴迷淫秽强迫症",
    "Ores Gained": "获得的矿石",
    "ores healed.": "矿石愈合。",
    "ores manufactured.": "制造的矿石。",
    "ores raised.": "提出的矿石。",
    "per second while training": "训练时每秒",
    "Pitchfork": "叉",
    "Raise dead ores from the graves.": "从坟墓里捡起死去的矿石。",
    "Reach a 100 hit combo.": "达到 100 连击。",
    "Reach a 200 hit combo.": "达到 200 连击。",
    "Refine": "精炼",
    "Responds to ore magnetism.": "响应矿石磁性。",
    "Rubber Conveyor Belt": "橡胶输送带",
    "Spooky dooky ores.": "诡异的怪异矿石。",
    "Stone Shovel": "石铲",
    "Study enuff...": "学习无...",
    "Teamwork": "团队合作",
    "The legendary golden goose that shits out ores.": "传说中会吐出矿石的金鹅。",
    "The OG": "OG",
    "The Stone Age": "石器时代",
    "These moves the things to there, that's all I know.": "这些将东西移到那里，这就是我所知道的。",
    "to level up.": "升级。",
    "Torches not included...": "不包括手电筒...",
    "Tractor": "拖拉机",
    "Training": "训练",
    "TRAINING SPE": "培训 SPE",
    "Trio": "三重奏",
    "Twill Rope": "斜纹绳",
    "UFO x10": "飞碟 x10",
    "Upgrade III": "升级三",
    "Upgrade IV": "升级四",
    "Wood Shovel": "木铲",
    "Wooden Compass": "木制指南针",
    "Worship Session": "崇拜会",
    "XP Gained": "获得的经验",
    "You are currently on": "您目前在",
    "You are gaining a global": "你正在获得一个全球性的",
    "You gain": "你获得",
    "You need": "你需要",
    "You will gain": "你会收获",
    "Your current generation level determines how much XP you get each second.": "您当前的世代等级决定了您每秒获得多少 XP。",
    ", every building production multiplier is increased by": "，每个建筑生产乘数增加",
    ". Visible in the": ".中可见",
    "[ active ]": "[ 已激活 ]",
    "[ passive ]": "[ 被动的 ]",
    "1 Random Ad Gear Equipment -": "1 随机广告装备设备 -",
    "100 - (receiverLuck + 1) / (attackerDex + 1": "100 - (接收人幸运 + 1) / (攻击者灵巧 + 1",
    "5 to 10 Eggs -": "5到10个宠物蛋 -",
    "achievements and research.": "成就和研究。",
    "ACTIVE": "已激活",
    "Adamantite Pant": "精金裤",
    "Adventure Map": "冒险地图",
    "agility comes from your agility level": "敏捷来自你的敏捷等级",
    "agility comes from your equips": "敏捷来自你的装备",
    "agility.": "敏捷。",
    "ALL": "全部",
    "all 3 stats": "所有 3 个统计数据",
    "All Buildings Percent OpS Up": "所有建筑物 OpS 百分比上升",
    "Allows for...": "允许...",
    "Allows you to hold a": "允许您持有一个",
    "Allows you to spend refined ores to": "允许您将精炼矿石用于",
    "Allows you to view boss stats in quest menu before completing the boss.": "允许您在完成 Boss 之前在任务菜单中查看 Boss 统计数据。",
    "and": "和",
    "are better than your current pickaxe, it gets equipped.": "比你现在的镐好，它装备好了。",
    "Are you sure you want to refine?": "你确定要精炼吗？",
    "armor comes from your armor level": "护甲来自你的护甲等级",
    "armor comes from your equips": "护甲来自你的装备",
    "armor.": "护甲。",
    "attack * strength / 6": "攻击 * 力量 / 6",
    "attacks per second (ApS": "每秒攻击（ApS",
    "Auto Pickaxe Pickup": "自动镐皮卡",
    "backup artifact": "备份工件",
    "Bagholding GME... who's with me.": "Bagholding GME...谁和我在一起。",
    "Blessings of the Combo God II": "组合神的祝福二",
    "Blessings of the Ore God": "矿神的祝福",
    "Bosscyclopedia": "老板百科",
    "Buffer": "增益状态",
    "Building Expansion": "建筑扩建",
    "cancel": "取消",
    "chance to crit": "暴击的几率",
    "Cloth Chest": "布胸甲",
    "Cloth Helmet": "布质头盔",
    "combo.": "组合。",
    "comes from achievements": "来自成就",
    "comes from your agility level percent bonus": "来自你的敏捷度百分比奖励",
    "comes from your armor level percent bonus": "来自你的护甲等级百分比奖励",
    "comes from your dexterity level percent bonus": "来自你的灵巧度百分比奖金",
    "comes from your hp level percent bonus": "来自你的 hp 等级百分比奖励",
    "comes from your luck level percent bonus": "来自你的运气等级百分比奖金",
    "comes from your speed level percent bonus": "来自你的速度等级百分比奖金",
    "comes from your strength level percent bonus": "来自你的力量等级百分比奖金",
    "Cooldown": "冷却",
    "crit chance": "致命一击几率",
    "Crit chance is calculated by": "暴击几率计算如下",
    "damage - armor * .1": "伤害 - 护甲 * .1",
    "Damage is calculated by": "伤害计算方式为",
    "damage on a target with no armor.": "对没有盔甲的目标造成伤害。",
    "Damage taken is calculated by": "受到的伤害由下式计算",
    "Decrease the cooldown of your combo shield by": "将连击护盾的冷却时间减少",
    "Decrease the time to hatch an egg by 10": "将孵化宠物蛋的时间减少 10",
    "decreases damage taken.": "减少受到的伤害。",
    "decreases the travel duration during quests.": "减少任务期间的旅行时间。",
    "dexterity comes from pets": "灵巧来自宠物",
    "dexterity comes from your dexterity level": "灵巧来自您的灵巧等级",
    "dexterity comes from your equips": "灵巧来自你的装备",
    "dexterity.": "灵巧。",
    "Diamond Pickaxe": "钻石镐",
    "dodge chance": "躲闪几率",
    "Dodge percentage is calculated by": "闪避百分比由下式计算",
    "Domain Expansion...": "域名扩展...",
    "Egg Carton": "宠物蛋盒",
    "Enhancement Slots": "增强槽",
    "Even More Starter Schools": "更多入门学校",
    "Every": "每一个",
    "Every level of HP increases max health by": "每一级生命值都会增加最大生命值",
    "Every point in strength increases your damage by": "力量的每一点都会增加你的伤害",
    "Expand the reach": "扩大覆盖面",
    "faster.": "快点。",
    "Flat OpC Up": "平面 OpC 向上",
    "Flat OpS Up": "平面操作",
    "For": "为了",
    "For every": "对于每一个",
    "free schools": "免费学校",
    "Gain a global bonus of": "获得全球奖金",
    "Gain another": "获得另一个",
    "generation levels": "世代等级",
    "Gives a flat": "给一个flat",
    "Go on quests to find greater rewards and even": "继续任务以找到更大的奖励，甚至",
    "Harder! Better! Faster! Stronger!": "更难！更好的！快点！更强！",
    "Hardness": "硬度",
    "HERO": "英雄",
    "Hero Armor Up": "英雄护甲提升",
    "Hero Hp Up": "英雄生命值提升",
    "hit chance": "击中几率",
    "Hit chance is calculated by": "命中几率由下式计算",
    "Hot Swappable": "支持热插拔",
    "How are you even playing this? Increase the": "你怎么还玩这个？增加",
    "How do rocks decide on a good steak? They look at the marbling": "岩石如何决定一块好牛排？他们看着大理石",
    "hp comes from your equips": "hp来自你的装备",
    "hp comes from your hp level": "hp 来自你的 hp 等级",
    "hp.": "生命值。",
    "Increase every building OpS by": "将每栋建筑的 OpS 提高",
    "Increase hero armor by": "增加英雄护甲",
    "Increase hero base hp by": "增加英雄基础生命值",
    "Increase OpC by": "将 OpC 增加",
    "Increase OpS by": "将 OpS 提高",
    "Increase Quarry production multiplier by 150": "将采石场产量乘数提高 150",
    "Increase Quarry production multiplier by 50": "将采石场产量乘数提高 50",
    "Increase your": "增加你的",
    "increases damage dealt.": "增加造成的伤害。",
    "increases the amount of damage you can take.": "增加你可以承受的伤害量。",
    "increases your": "增加你的",
    "Incubation Speed I": "孵化速度 I",
    "Incubator": "孵化器",
    "Iron Weapon": "铁兵器",
    "is well... the amount of damage you deal.": "很好......你造成的伤害量。",
    "Legally Blind": "合法盲人",
    "level": "等级",
    "luck comes from your equips": "运气来自你的装备",
    "luck comes from your luck level": "运气来自你的运气等级",
    "luck.": "运气。",
    "max size by": "最大尺寸",
    "Mo Incubators": "钼培养胸甲",
    "more free schools": "更多免费学校",
    "Multitasker": "多任务处理",
    "mysterious artifacts": "神秘的文物",
    "Not a treasure map.": "不是藏宝图。",
    "of agility increases the agility from equips by": "敏捷增加装备的敏捷",
    "of armor increases the armor from equips by": "护甲增加装备的护甲",
    "of dexterity increases the dexterity from equips by": "灵巧度增加装备的灵巧度",
    "of HP increases the hp from equips by": "的 HP 增加装备的 hp",
    "of luck increases the luck from equips by": "运气增加装备的运气",
    "of speed increases the speed from equips by": "速度增加装备的速度",
    "of strength increases the strength from equips by": "力量增加装备的力量",
    "of your buildings.": "你的建筑物。",
    "on all sources of ore income.": "所有矿石收入来源。",
    "Onwards to adventure!": "继续冒险！",
    "OOOOCD": "OOOOCD",
    "Ore-Sniffing Doggies": "矿石嗅探犬",
    "per second.": "每秒。",
    "Percent OpC Up": "OpC 上升百分比",
    "Pickaxes are now automatically picked up after": "镐现在会在之后自动拾取",
    "points of agility increases your passive attack speed by": "敏捷点数会增加你的被动攻击速度",
    "points of speed, your travel speed is increased by": "速度点，您的行进速度增加",
    "Pop and play. Allows swapping between research upgrades. Current progress will be saved.": "流行和播放。允许在研究升级之间进行交换。当前进度将被保存。",
    "Quests now have a chance of dropping an egg.": "任务现在有几率掉落一个宠物蛋。",
    "r/mk": "r/mk",
    "refine": "精炼",
    "refined ores.": "精炼矿石。",
    "Refinement": "精炼",
    "REFINEMENT!": "精炼！",
    "seconds. If": "秒。如果",
    "Sharpness": "锐度",
    "Shield Polish": "盾牌抛光剂",
    "speed": "速度",
    "speed comes from your equips": "速度来自你的装备",
    "speed comes from your speed level": "速度来自你的速度等级",
    "speed.": "速度。",
    "Start off with": "从开始",
    "Starter Schools": "入门学校",
    "Stat Lv.": "属性等级",
    "Stats now auto level up when reaching xp cap.": "现在，当达到 XP 上限时，统计数据会自动升级。",
    "strength comes from your equips": "力量来自你的装备",
    "strength comes from your strength level": "力量来自你的力量等级",
    "strength.": "力量。",
    "tab.": "标签。",
    "Tenant Intimidation": "恐吓租户",
    "The almighty Combo God is pleased by devotion. You now gain another bonus of up to": "全能的组合神因奉献而高兴。您现在可以获得高达",
    "the level of your buildings for a flat percent increase in its production.": "你的建筑物的等级使其产量增加一个百分比。",
    "The Ore God blesses you. You feel weird...": "矿神祝福你。你觉得奇怪...",
    "Titanium Shoe": "钛鞋",
    "to your OpC and OpS when reaching": "到达时到您的 OpC 和 OpS",
    "Too the Moon": "前往月球",
    "Train your vocal cords to yell and scowl longer. Increase the duration of": "训练你的声带更长时间地大喊大叫和皱眉。增加持续时间",
    "Trainer": "培训师",
    "TRAINING AGI": "训练 敏捷",
    "TRAINING ARM": "训练 护甲",
    "Unlock": "解锁",
    "upgrade": "升级",
    "Vocal Lessons": "声乐课",
    "Walking Cane": "手杖",
    "Watch the latest More Ore devlog on YouTube! Click here to check it out!": "在 YouTube 上观看最新的 More Ore 开发日志！点击这里查看！",
    "weapon attack + (weapon attack * strength) / 6": "武器攻击+（武器攻击*力量）/ 6",
    "You are completing quests": "你正在完成任务",
    "You are currently attacking": "您当前正在攻击",
    "You currently deal": "您目前交易",
    "You currently have": "你目前有",
    "You currently have a": "您目前有一个",
    "You will keep": "你会保留",
    "You will keep your artifact": "你会保留你的神器",
    "You will keep your current combo of": "您将保留当前的组合",
    "You will keep your refined ores.": "你会保留你的精炼矿石。",
    "You will lose": "你会失去",
    "your buildings and upgrades.": "你的建筑和升级。",
    "your equips.": "你的装备。",
    "Your hero can now Train and Quest at the same time.": "你的英雄现在可以同时训练和探索。",
    "your ores.": "你的矿石。",
    "your pets and eggs": "你的宠物和宠物蛋",
    "your trained levels on your hero.": "您对英雄的训练等级。",
    "Where do stones sleep? In bedrock.": "石头睡在哪里？在基岩中。",
    "[follower achievement]": "[追随者成就]",
    "Agility I": "敏捷 I",
    "Agility II": "敏捷 II",
    "Agility III": "敏捷 III",
    "Agility IV": "敏捷 IV",
    "Break the Among Us rock.": "打破我们中间的摇滚。",
    "Break The Rock.": "打破岩石。",
    "Centennial": "百年纪念",
    "Click on a bat": "点击一个蝙蝠",
    "Click on a gold nugget.": "点击金块。",
    "Combo Devil": "组合恶魔",
    "Cult Following": "邪教追随",
    "Dexterity II": "灵巧 II",
    "Doubletime": "双倍时间",
    "Educate": "教育",
    "Egg I": "宠物蛋 I",
    "Foggy": "有雾的",
    "Groggy": "昏昏沉沉的",
    "Hatch your first pet": "孵化你的第一只宠物",
    "Hehe Funny Number III": "呵呵搞笑 III",
    "Hungover": "宿醉",
    "Insightful": "有见地",
    "it's about drive, it's about power, we stay hungry, we devour, put in the work, put in the hours, and take what's ores": "这是关于驱动力，这是关于力量，我们保持饥饿，我们吞噬，投入工作，投入时间，并采取什么是矿石",
    "Lots of times": "很多次",
    "Luck I": "幸运 I",
    "Luck II": "幸运 II",
    "Luck III": "幸运 III",
    "Miss 50 gold nuggets.": "错过 50 块金块。",
    "No. 2 Pencil": "2号铅笔",
    "OOCD": "OOCD",
    "OOOCD": "OOCD",
    "ores from Schools in a single run.": "一次运行从学校获得的矿石。",
    "Own more than 100 buildings.": "拥有100多座建筑。",
    "Permanently increase agility by 5": "永久增加5点敏捷",
    "Permanently increase armor by 5": "永久增加5点护甲",
    "Permanently increase dex by 5": "永久增加 5 点 dex",
    "Permanently increase hp by 5": "永久增加 5 点生命值",
    "Permanently increase luck by 5": "永久增加5点运气",
    "Permanently increase strength by 5": "永久增加5点力量",
    "Pet your pet": "宠爱你的宠物",
    "Play for more than a week": "玩了一个多星期",
    "Quadratime": "Quadratime",
    "Racer": "赛车手",
    "Rain Proof!": "防雨！",
    "Reach 2 auto attacks per second": "每秒达到 2 次自动攻击",
    "Reach Generation 10": "达到第 10 代",
    "Reach lv.10 agility": "达到 lv.10 敏捷",
    "Refine for your first time!": "第一次细化！",
    "Shiny Nuggy": "闪亮的纳吉",
    "Test ready!": "测试准备好了！",
    "Time to get Swole": "是时候获得 Swole 了",
    "Took me like 3 hours to implement this...": "我花了大约 3 个小时来实现这个......",
    "Unlock pets": "解锁宠物",
    "Unlock training": "解锁训练",
    "Upgrade II": "升级 II",
    "Well Renowned": "名声在外",
    "[common]": "[普通]",
    "[Common]": "[普通]",
    "[common] [EQUIPPED]": "[普通] [已装备]",
    "[common] [TYPE - chalk]": "[普通] [类型 - 粉笔]",
    "Abandon Pet": "抛弃宠物",
    "Accept Quest": "接受任务",
    "agility": "敏捷",
    "Bandit Camp": "强盗营地",
    "Barren Outskirts": "贫瘠的郊区",
    "Blessings of the Combo God": "组合神的祝福",
    "Bloons420, the Basalt": "Bloons420，玄武岩",
    "bonus to your OpS and OpC.": "对您的 OpS 和 OpC 的奖励。",
    "Castle Slums": "城堡贫民窟",
    "Cavern Depths": "洞穴深处",
    "Cavern Exit": "洞穴出口",
    "click or drag up to equip": "单击或向上拖动以装备",
    "Completed On": "完成于",
    "Darkness... It's all you've ever known.": "黑暗……这就是你所知道的一切。",
    "Desparate Thief": "绝望的小偷",
    "dexterity": "灵巧",
    "Egg Drop Chance": "蛋掉落几率",
    "Empty Wasteland": "空旷的荒地",
    "Equip Pet": "装备宠物",
    "Equipped Pets": "装备宠物",
    "Equips per Run": "每次运行装备",
    "Favorite Pet": "收藏宠物",
    "Feature not yet implemented. Coming soon...": "功能尚未实现。快来了...",
    "Fecal Mountain": "粪山",
    "fly, the Chalk": "飞，粉笔",
    "Frail Scavenger": "虚弱的清道夫",
    "Gen. XP": "根 XP",
    "Hatch All": "全部孵化",
    "Hatched All": "全部孵化",
    "Incubation": "孵化",
    "Incubators": "孵化器",
    "Is this the light at the end of the tunnel?": "这是隧道尽头的光吗？",
    "Lowly Bandit": "卑贱的强盗",
    "Max Eggs Per Run": "每次运行的最大宠物蛋数",
    "Momma Rat": "鼠妈妈",
    "Next update coming soon™": "下一次更新即将推出™",
    "Normal Egg": "普通蛋",
    "OpS * 0.1 * Quest Duration": "OpS * 0.1 * 任务持续时间",
    "Pet Pen": "宠物笔",
    "Quest Duration": "任务持续时间",
    "Quest Rewards": "任务奖励",
    "Quest Stats": "任务统计",
    "Quick Hatch": "快速孵化",
    "Radroach": "蟑螂",
    "Rank": "段位",
    "Rat Den": "鼠窝",
    "Rat King": "鼠王",
    "Rat Kingdom": "老鼠王国",
    "Rat Nest": "鼠窝",
    "Rat Soldier": "鼠兵",
    "Reputation": "声誉",
    "Rusty Manhole": "生锈的沙井",
    "Sanitation Station": "环卫站",
    "Sentient Poo": "有情便便",
    "Sewer Clown": "下水道小丑",
    "Sewer Tunnels": "下水道隧道",
    "Shamadere, the Pumice": "Shamadere，浮石",
    "Somebody": "某人",
    "SORT ALL": "全部排序",
    "Swamp Thickets": "沼泽灌木丛",
    "This isn't what you imagined life outside would be like.": "这不是你想象的外面的生活会是什么样子。",
    "Times Completed": "完成时间",
    "Total Attempts": "总尝试次数",
    "Unequip Pet": "解除宠物",
    "Watching an ad doesn't give me money! Only when you click on the ad! So if something interests you and you want to support the dev, click away :": "看广告不给我钱！只有当你点击广告！因此，如果您感兴趣并且想要支持开发人员，请点击离开：",
    "You are currently getting a": "您目前正在获得",
    "Your Shadow": "你的影子",
    "\n            HATCH": "\n            孵化",
    "[\n                Legendary  ]": "[\n                传奇  ]",
    "XP": "经验值",
    "ORES": "矿石",
    "[ quest-active ]": "[任务激活]",
    "[common] [TYPE - pyrite]": "[普通] [类型 - 黄铁矿]",
    "A quest is already in progress": "一个任务已经在进行中",
    "Adamantite Shoe": "精金鞋",
    "Alien Pant": "外星人裤子",
    "Alien Shoe": "异形鞋",
    "Allows for pets who have the same type to be merged together": "允许将具有相同类型的宠物合并在一起",
    "An incessant buzz fills the air.": "空气中充满了不断的嗡嗡声。",
    "animated": "动画",
    "Are you sure you want to abandon this pet?": "你确定要放弃这只宠物吗？",
    "ARTIFACT RETRIEVED -": "回收的神器——",
    "attacked": "被攻击",
    "Auto Quester 5000": "自动探索者 5000",
    "B Lister": "水疱",
    "Bandit Bathroom": "强盗浴室",
    "Bandit Tent": "强盗帐篷",
    "Base pickaxe on refine starts with": "精炼基础镐开始于",
    "Big Bite": "大咬",
    "BIG BITE": "大咬",
    "Bite": "咬",
    "BITE": "咬",
    "Black Swordsman": "黑剑客",
    "Blessings of the Combo God III": "组合神的祝福III",
    "Blood Rush": "血冲",
    "Bobby'); DROP TABLE STUDENTS; --, the Chalk": "鲍比');放弃表学生； ——粉笔",
    "Bollywood": "宝莱坞",
    "Boots of Mobility": "流动之靴",
    "but missed": "但错过了",
    "by a": "由一个",
    "C Lister": "C李斯特",
    "Cardboard Chest": "纸板胸甲",
    "Cardboard Helmet": "纸板头盔",
    "Cardboard Pant": "纸板裤",
    "Cardboard Shoe": "纸板鞋",
    "Cardboard Weapon": "纸板武器",
    "casted": "铸造",
    "CASTED": "铸造",
    "Castle Entrance": "城堡入口",
    "Castle Ghettos": "城堡贫民区",
    "Child Gang": "童帮",
    "Christine, the Eclogite": "榴辉石克里斯汀",
    "Christine, the Quartz": "克里斯汀，石英",
    "Click to equip": "点击装备",
    "Click to Hatch": "点击孵化",
    "Cloth Accessory": "布艺配饰",
    "Cloth Pant": "布裤",
    "Cloth Shoe": "布鞋",
    "Cloud of Flies": "苍蝇云",
    "Common Artifact": "普通神器",
    "completed": "已完成",
    "Cripple": "削弱",
    "Criterias": "标准",
    "Cult of the Lamb is a pretty sick game.": "羔羊崇拜是一个非常恶心的游戏。",
    "damage": "损害",
    "damage.": "损害。",
    "Dark Lord": "黑暗领主",
    "Deal more than 100 damage from a hit.": "击中造成超过 100 点伤害。",
    "Diamond Accessory": "钻石配件",
    "Double Stab": "双刺",
    "DOUBLE STAB": "双刺",
    "Egg Carton is full": "宠物蛋盒装满了",
    "EGGS": "蛋",
    "EMPTY PET SLOT": "空宠物槽",
    "Enlightened": "开明",
    "Epic Artifact": "史诗神器",
    "Equilibrium": "平衡",
    "Equipped": "配备",
    "EQUIPPED ITEM": "装备物品",
    "fly": "飞",
    "Followers": "追随者",
    "for": "为了",
    "Forwaken, the Pumice": "被遗忘的浮石",
    "Gather": "收集",
    "Gatherer": "采集者",
    "Giant Syndrome": "巨人症候群",
    "Gold Accessory": "黄金饰品",
    "Gold Chest": "金胸甲",
    "Gold Helmet": "金头盔",
    "Gold Pant": "金裤子",
    "Gold Rush": "淘金热",
    "Gold Shoe": "金鞋",
    "Gold Weapon": "黄金武器",
    "Grow your cul.. I mean amass a large following.": "培养你的文化。我的意思是积累大量的追随者。",
    "Hardstuck D4?": "硬着头皮D4？",
    "HATCH": "孵化",
    "Hatched a basalt": "孵化了玄武岩",
    "Hatched a chalk": "孵化了一支粉笔",
    "Hatched a eclogite": "孵化了榴辉石",
    "Hatched a pumice": "孵化了一块浮石",
    "Hatched a pyrite": "孵化了一个黄铁矿",
    "Hatched a quartz": "孵化了一个石英",
    "Heal": "愈合",
    "Hedge Fund": "对冲基金",
    "Hero Strength Up": "英雄实力提升",
    "HIGHER DAMAGE": "更高的伤害",
    "HIGHER HARDNESS": "更高的硬度",
    "HIGHER SHARPNESS": "更高的清晰度",
    "Increase all hero stats by": "增加所有英雄属性",
    "Increase armor by": "增加护甲",
    "Increase hero hp by": "增加英雄血量",
    "Increase hero speed by": "增加英雄速度",
    "Increase hero strength by": "增加英雄力量",
    "Increase HP by": "增加HP",
    "Increase strength by": "增加力量",
    "Incubate All": "孵化所有",
    "incubating": "孵化",
    "Influencer": "影响者",
    "Iron Accessory": "铁配件",
    "Iron Chest": "铁胸甲",
    "Iron Helmet": "铁盔",
    "Iron Pant": "铁裤",
    "Iron Shoe": "铁鞋",
    "It's a hard rock life... for us.": "这是艰难的生活……对我们来说。",
    "Leather Accessory": "皮革配饰",
    "Leather Chest": "皮胸甲",
    "Leather Helmet": "皮头盔",
    "Leather Pant": "皮裤",
    "Leather Shoe": "皮鞋",
    "Legendary Artifact": "传奇神器",
    "Located in what looks to be a run down Jazz Club.": "位于看起来是一个破败的爵士俱乐部。",
    "Lube": "润滑油",
    "Lubed Assailant": "润滑攻击者",
    "luck": "运气",
    "Minecrafter": "我的世界",
    "Missed": "错过",
    "Mohs Hardness Test": "莫氏硬度测试",
    "More Ore is now available to be wishlist on Steam! Click here to wishlist!": "更多矿石现已加入 Steam 愿望单！点击这里加入愿望清单！",
    "More Starter Schools": "更多入门学校",
    "Multi Stab": "多刺",
    "MULTI STAB": "多刺",
    "n3uro, the Eclogite": "n3uro，榴辉石",
    "NEW ITEM": "新物品",
    "Not enough space for a new pet": "没有足够的空间容纳新宠物",
    "Now you're thinking with portals": "现在您正在考虑使用门户网站",
    "Ominous buildings loom in the distance": "远处隐约可见不祥的建筑",
    "on": "上",
    "Once per boss fight, you can heal your hero for": "每次boss战一次，你可以治疗你的英雄",
    "Ore Cache": "矿石缓存",
    "ores from Stone Huts in a single run.": "石屋中的矿石。",
    "parallax": "视差",
    "Permanently increase hero dex by 5": "永久增加英雄 dex 5",
    "Pet Abandoned": "被遗弃的宠物",
    "Pet Leveling": "宠物练级",
    "Pet Teleportation": "宠物传送",
    "Pickup if new item has": "如果新项目有",
    "Plain Egg": "普通宠物蛋",
    "Plastic Accessory": "塑料配件",
    "Plastic Chest": "塑料胸甲",
    "Plastic Helmet": "塑料头盔",
    "Plastic Pant": "塑料裤",
    "Plastic Shoe": "塑料鞋",
    "Plastic Weapon": "塑料武器",
    "Platinum Accessory": "铂金配件",
    "Platinum Chest": "铂金胸甲",
    "Platinum Helmet": "铂金头盔",
    "Platinum Pant": "铂金裤子",
    "Platinum Shoe": "铂金鞋",
    "Platinum Weapon": "白金武器",
    "Pocket Lube": "袖珍润滑油",
    "POCKET LUBE": "袖珍润滑油",
    "Poo on a Stick": "便便在棍子上",
    "Quest Complete": "任务完成",
    "QUEST FAILED": "任务失败",
    "QUEST SUCCESS": "任务成功",
    "Ravenous Strikes": "贪婪的罢工",
    "Redo Quest": "重做任务",
    "REFINED": "精制",
    "Rewards": "奖励",
    "Scavenger": "清道夫",
    "seconds, all manual strikes towards the boss deals an additional": "秒，所有对boss的手动攻击都会造成额外的",
    "Shameless plug... I know...": "无耻的塞子……我知道……",
    "Silver Accessory": "银饰",
    "Silver Chest": "银胸甲",
    "Silver Helmet": "银头盔",
    "Silver Pant": "银色裤子",
    "Silver Shoe": "银鞋",
    "Smash rocks to make em stronger... makes sense.": "粉碎岩石使它们变得更强壮……是有道理的。",
    "STATE: completed": "状态：已完成",
    "STATE: incubating": "状态：孵化",
    "Steel Accessory": "钢配件",
    "Steel Chest": "钢胸甲",
    "Steel Helmet": "钢盔",
    "Steel Pant": "钢裤",
    "Steel Shoe": "钢鞋",
    "Steel Weapon": "钢铁武器",
    "Stone Weapon": "石头武器",
    "strength": "力量",
    "Surrounded by filth and poverty, one building remains pristine.": "被肮脏和贫穷包围着的一栋建筑仍然保持着原始状态。",
    "Teleport these pets at Mach 10 speeds. You are now able to change/level pets during a quest": "以 10 马赫的速度传送这些宠物。您现在可以在任务期间更改/升级宠物",
    "The almighty Combo God has noticed your dedication. You now gain a bonus of up to": "全能的组合神已经注意到了你的奉献精神。您现在可以获得高达",
    "The almighty Combo God is satisfied with your loyalty. You now gain a final bonus of up to": "全能的组合神对你的忠诚感到满意。您现在获得的最终奖金高达",
    "The best way to test a volcano is to throw a rock in it... or yourself.": "测试火山的最好方法是往里面扔一块石头……或者你自己。",
    "There's ore where that came from.": "那是从哪里来的矿石。",
    "Thieves Guild": "盗贼公会",
    "Titanium Chest": "钛胸甲",
    "Titanium Helmet": "钛头盔",
    "Toggle Auto Pickaxe Pickup": "切换自动镐拾取",
    "TRAINING ARM & QUESTING": "训练手臂和任务",
    "Trashed": "丢弃",
    "Tripletime": "三倍时间",
    "Trot on with speed and poise": "保持速度和平衡",
    "Uncommon Artifact": "罕见神器",
    "Unfavorite Pet": "取消收藏宠物",
    "Unique Artifact": "独特的神器",
    "Unlocks the Auto Quester 5000.": "解锁 Auto Quester 5000。",
    "Wallhacks": "壁垒",
    "Weaken": "削弱",
    "WEAKEN": "削弱",
    "Wood Weapon": "木制武器",
    "Yao, the Basalt": "玄武岩姚",
    "You Found": "你发现了",
    "OpossumLord, the Pumice": "负鼠领主，浮石",
    "Bloons420, the Quartz": "Bloons420，石英",
    "Clicky Squish Buttons": "可点击的挤压按钮",
    "Evolution": "进化",
    "Gauze Pads": "纱布垫",
    "In Use": "正在使用",
    "Increase School base production by 50": "将学校基地产量提高 50",
    "Increase Stone Hut base production by 50": "石屋基地产量增加 50",
    "Iron Shovel": "铁锹",
    "Less sorting, more ore.": "更少的分拣，更多的矿石。",
    "Not even grass can stop us now.": "现在连草都挡不住我们。",
    "Ore Filter": "矿石过滤器",
    "Rotary Cutter": "旋转切刀",
    "These go next to the Squishy Click Buttons.": "这些在 柔软的点击按钮 旁边。",
    "Upgrade V": "升级五",
    "You would think a day of worship is one less day of work but somehow it works out to more ore!": "你会认为一天的敬拜是少一天的工作，但不知何故它会产生更多的矿石！",
    "Call me Pointdexter": "叫我指点器",
    "Equipped Lead Pickaxe": "装备铅镐",
    "Equipped Pointy Gold Pickaxe": "装备尖尖的金镐",
    "Equipped Silver Pickaxe": "装备银镐",
    "Hulk Smash": "浩克粉碎",
    "Increase all pickaxe hardness by": "将所有镐硬度提高",
    "Increase school production multiplier by": "将学校生产乘数提高",
    "Me angry. Me smash.": "我很生气。 我粉碎。",
    "more free schools.": "更多免费学校。",
    "Not enough ores to train": "没有足够的矿石来训练",
    "Pickaxe Hardness Up": "镐硬度上升",
    "Your next click deals": "您的下一次点击交易",
    "your OpC.": "你的 OpC。",
    "IDLE": "空闲",
    "Click to swap/equip": "点击更换/装备",
    "Time left": "时间剩余",
    "Tin Pickaxe": "锡镐",
    "Lead Pickaxe": "铅镐",
    "ITEMS FOUND": "找到物品",
    "luck comes from pets": "幸运来自宠物",
    "Not Active": "未激活",
    "Razor Copper Pickaxe": "剃刀铜镐",
    "TRAINING DEX": "训练 灵巧",
    "TRAINING LUC": "训练 幸运",
    "TRAINING STR": "训练 力量",
    "TRAINING HP": "训练 生命值",
    "Baby Heal": "婴儿愈合",
    "BABY HEAL": "婴儿康复",
    "BAM": "迷惑",
    "BANG": "猛击",
    "BOOM": "BOOM",
    "CRIT!": "暴击！",
    "Cuts all damage in half for the next couple attacks": "在接下来的几次攻击中将所有伤害减半",
    "Doubles attack speed until the end of the battle.": "攻击速度翻倍，直到战斗结束。",
    "Durable Copper Pickaxe of Keen Eyes": "敏锐之眼的耐用铜镐",
    "Enrage": "激怒",
    "ENRAGE": "激怒",
    "Equipped Durable Copper Pickaxe of Keen Eyes": "装备敏锐之眼的耐用铜镐",
    "Equipped Wood Pickaxe": "装备木镐",
    "Intuition": "直觉",
    "Permanently increase hero dex by 10": "永久增加英雄 灵巧 10",
    "Self": "自己",
    "SLAP": "拍击",
    "SMACK": "拍打",
    "Strong Stone Pickaxe": "强力石镐",
    "THWOMP": "重击",
    "TRAINING HP & QUESTING": "训练 HP 和 QUESTING",
    "WHACK": "敲打",
    "Wood Pickaxe": "木镐",
    "Hp XP Gained": "获得的生命值经验值",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "LUK": "幸运",
    "idle": "空闲",
    "hp": "生命值",
    "APS": "攻击每秒",
    "ATK": "攻击",
    "Duo": "Duo",
    "ARM": "护甲",
    "AGI": "敏捷",
    "LUC": "幸运",
    "DEX": "灵巧",
    "STR": "力量",
    "SPE": "速度",
    "are generating": "正在产生",
    'are currently generating': '现在正在生产',
    "DISCORD": "DISCORD",
    'In ore name we pray, amen.': '我们祈祷，阿门。',
    'Research Power': '研究效果',
    'Diggy diggy hole.': '挖洞，挖洞。',
    'Praise to ye Old Ore Gods.': '赞美你们古老的矿石神。',
    'Rock pun here': '岩石双关语在这里',
    'Research Power Up': '研究效果提升',
    'Requires': '需要',
    'Combo Baby': '连击宝贝',
    'Fetch quests are the greatest aren\'t they?': '获取任务是最棒的不是吗?',
    'ores per second while researching.': '矿石 每秒，当你研究时。',
    'Onwards to adventure! Go on quests to find greater rewards and even mysterious artifacts!': '开始冒险吧!继续寻找更大的奖励，甚至是神秘的文物!',
    'Fragility Spectacles': '易碎眼镜',
    'I can see... I can FIGHT!': '我能看到……我能战斗!',
    'As you can tell, these are pretty lame... Submit your own to /u/name_is_Syn': '正如你所看到的，这些很差劲……提交你自己的到/u/name_is_Syn',
    'Allows you to spot "weak spots" within the ore. Hitting the weak spot generates 5x the normal amount.': '让你发现矿石的“弱点”。击中弱点会产生5倍于正常数量的能量。',
    ' research': '研究',
    'Research Power': '研究效果',
    'The poop helps the ore mature.': '粪便有助于矿石的成熟。',
    'Novice Miner': '新手矿工',
    'What is a rocks favorite fruit? ... Pom-a-granite': '岩石最喜欢的水果是什么?…花岗岩',
    'Manure Spreader': '撒肥机',
    'These puns sure are all ore nothing': '这些双关语毫无意义',
    'There are a few gems amongst all these terrible rock puns': '在所有这些可怕的岩石双关语中有一些宝石',
    'Rocks really rock!': '岩石真摇滚!',
    'I can\'t believe I\'m googling rock puns right now': '真不敢相信我现在在谷歌上搜索摇滚双关语',
    'is generating': '正在生产',
    'Each Farm generates': '每个农场生成',
    'Don\'t take life for granite': '不要为花岗岩而死',
    'Composition Notebooks': '作文笔记本',
    'What happens when you throw a blue rock in the red sea? ... It gets wet': '如果你把一块蓝石扔进红海会发生什么?…它会湿',
    '[ School Production Multiplier': '[学校生产乘数',
    '[ Farm Production Multiplier': '[农场生产乘数',
    'This totally makes sense...': '这完全有道理…',
    'Teach students about the wonders of ore.': '教学生关于矿石的神奇之处。',
    'of your total OpS': '你的全部矿石生产每秒（OpS）',
    'Jesus christ Marie, they\'re minerals!': '上帝啊，它们是矿物质!',
    'Increases the production multiplier of Schools by 1': '使学校的生产乘数增加1',
    'Increases the production multiplier of Farms by 1': '使农场的生产乘数增加1',
    'Increases the production multiplier of Quarries by 1': '使采石场的生产乘数增加1',
    'Cultivate the lands for higher quality ores.': '耕种土地以获得更高质量的矿石。',
    'Each School generates': '每个学校产生',
    'College ruled!': '大学说了算!',
    'Break your first rock': '打破你的第一块石头',
    'All rock and no clay makes you a dull boy (or girl': '只有石头没有泥土，会使你成为一个迟钝的男孩(或女孩',
    'Did you see that cleavage? Now that\'s some gneiss schist.': '你看到分裂了吗？ 现在，这是一些片麻岩片岩。',

    //原样
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'Patron': 'Patron',
    'x': 'x',
    "V": "V",
    "VI": "VI",
    "VII": "VII",
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'Discord': 'Discord',
    'Patreon': 'Patreon',
    'Steam': 'Steam',
    'Syns Studio': 'Syns Studio',
    'HP': '生命值',
    'X': 'X',
    "BOSS": "BOSS",
    'VS': 'VS',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Power Needed: ": "力量需求: ",
    "Refined Ores: ": "提炼矿石: ",
    "[repeatable lv.": "[可重复 等级",
    "Farm ": "农场 ",
    "School ": "学校 ",
    "Church ": "教堂 ",
    "Quarry ": "采石场 ",
    'Schools ': '学校 ',
    'Farms ': '农场 ',
    "Quarrys ": "采石场 ",
    "Churchs ": "教堂 ",
    "WTF ": "什么鬼 ",
    'Schools ': '学校 ',
    "Quarries ": "采石场 ",
    "Churches ": "教堂 ",
    "Oreverse Mastery ": "逆向精通 ",
    "O.A.R.D.I.S. Mastery ": "O.A.R.D.I.S. 精通 ",
    "O.A.R.D.I.S. ": "O.A.R.D.I.S. ",
    "Armor ": "护甲 ",
    "Pet Power ": "宠物力量 ",
    "Oreverse ": "逆向 ",
    "Monolith Mastery ": "单体精通 ",
    "Monolith ": "巨石 ",
    "Sky Castle Mastery ": "天空之城精通 ",
    "Sky Castle ": "天空之城 ",
    "The Collector ": "收藏家 ",
    "UFO Mastery ": "UFO 精通  ",
    "Stone Hut ": "石屋 ",
    "Mastery ": "精通 ",
    "Strength ": "力量 ",
    "Speed ": "速度 ",
    "Egg Trasher ": "打宠物蛋器 ",
    "Hospital Mastery ": "医院精通 ",
    "Hatcheries ": "孵化场 ",
    "Shiny Hunter ": "闪亮的猎人 ",
    "Trasher ": "捣毁者 ",
    "[\n                Epic  •  Lv.": "[\n                史诗  •  等级 ",
    "[ Skill ID: ": "[ 技能 ID: ",
    "[\n                Epic": "[\n                史诗",
    "[\n                Legendary  •  Lv.": "[\n                传奇  •  等级 ",
    "[\n                Uncommon  •  Lv.": "[\n                罕见  •  等级 ",
    "[\n                Mythic  •  Lv.": "[\n                神话  •  等级 ",
    "luck / ": "幸运 / ",
    "LV: ": "等级：",
    "ID: ": "ID: ",
    " •  Epic  •  Lv.": " •  史诗  •  等级",
    " •  Legendary  •  Lv.": " •  传奇  •  等级",
    " •  Mythic  •  Lv.": " •  神话  •  等级",
    " •  Uncommon  •  Lv.": " •  罕见  •  等级",
    " •  Common  •  Lv.": " •  普通  •  等级",
    " • \n                Unique  •  Lv.": " • \n                独特  •  等级",
    " • \n                Uncommon  •  Lv.": " • \n                罕见  •  等级",
    " • \n                Rare  •  Lv.": " • \n                稀有  •  等级",
    " • \n                Mythic  •  Lv.": " • \n                神话  •  等级",
    " • \n                Legendary  •  Lv.": " • \n                传奇  •  等级",
    " • \n                Epic  •  Lv.": " • \n                史诗  •  等级",
    " • \n                Common  •  Lv.": " • \n                普通  •  等级",
    "Incubator #": "孵化器 #",
    "Factory x": "工厂 x",
    "Hospital x": "医院 x",
    "Crypt x": "墓穴 x",
    "UFO x": "UFO x",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " Thousand": " 千",
    " hit combo": " 连击",
    " sec": " 秒",
    " Vision": " 视野",
    " Random Legendary Pickaxe -": " 随机传奇镐 -",
    " hr raw": " 小时 原始",
    " m raw": " 分 原始",
    "[Hotkey: R]": "[快捷键: R]",
    "[Hotkey: H]": "[快捷键: H]",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^(\d+)\:(\d+)$/,
    /^(\d+)\:(\d+)\:(\d+)$/,
    /^([\d\.]+) Million\/([\d\.]+) Million$/,
    /^fix(.+)$/,
    /^v.(.+)$/,
    /^removed(.+)$/,
    /^added(.+)$/,
    /^updated(.+)$/,
    /^Released on(.+)$/,
    /^XP ([\d\.]+) K\/([\d\.]+) K$/,
    /^XP ([\d\.]+)\/([\d\.]+) K$/,
    /^x([\d\.]+)$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+) XP$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) Million$/,
    /^([\d\.]+) Billion$/,
    /^([\d\.]+)$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^Fast Forward (.+) minutes \-$/, '快进 $1 分钟 \-'],
    [/^(.+), the Pyrite$/, '$1，黄铁矿'],
    [/^Reach (.+) Reputation to unlock this$/, '达到 $1 声望即可解锁'],
    [/^Click on the left torch (.+) times.$/, '单击左侧火炬 $1 次。'],
    [/^Click (.+) gold nuggets.$/, '点击 $1 金块。'],
    [/^Pick up (.+) items.$/, '拾取 $1 物品。'],
    [/^Discard (.+) items.$/, '丢弃 $1 物品。'],
    [/^Reach a (.+) hit combo.$/, '达到 $1 连击。'],
    [/^Reach (.+) OpS.$/, '达到 $1 OpS（矿石每秒）。'],
    [/^Reach lv.(.+) luck$/, '达到 等级$1 幸运'],
    [/^Reach lv.(.+) agility$/, '达到 等级$1 敏捷'],
    [/^Reach lv.(.+) speed$/, '达到 等级$1 速度'],
    [/^Reach lv.(.+) dexterity$/, '达到 等级$1 灵巧'],
    [/^Reach lv.(.+) strength$/, '达到 等级$1 力量'],
    [/^Reach lv.(.+) armor$/, '达到 等级$1 护甲'],
    [/^Reach (.+) armor$/, '达到 $1 护甲'],
    [/^Reach (.+) luck$/, '达到 $1 幸运'],
    [/^Reach (.+) hp$/, '达到 $1 生命值'],
    [/^Reach (.+) dex$/, '达到 $1 灵巧'],
    [/^Reach (.+) agility$/, '达到 $1 敏捷'],
    [/^Reach (.+) strength$/, '达到 $1 力量'],
    [/^Reach (.+) speed$/, '达到 $1 速度'],
    [/^(\d+) TOTAL \| (\d+) IDLE$/, '总计 $1 \| 空闲 $2'],
    [/^lv.(\d+)$/, '等级 $1'],
    [/^Lv.(\d+)$/, '等级 $1'],
    [/^Lv. (\d+)$/, '等级 $1'],
    [/^([\d\.]+) Million\/([\d\.,]+)$/, '$1 Million\/$2'],
    [/^([\d\.]+) Thousand\/([\d\.,]+)$/, '$1 千\/$2'],
    [/^([\d\.]+) Thousand xp$/, '$1 千 经验值'],
    [/^([\d\.]+) hp$/, '$1 生命值'],
    [/^([\d\.]+) Thousand hp$/, '$1 千 生命值'],
    [/^(\d+) seconds$/, '$1 秒'],
    [/^(\d+) min$/, '$1 分钟'],
    [/^(\d+) hour$/, '$1 小时'],
    [/^(\d+) min (\d+)$/, '$1 分钟 $2'],
    [/^(\d+) hour (\d+) min (\d+)$/, '$1 小时 $2 分钟 $3'],
    [/^(\d+) hours (\d+) min$/, '$1 小时 $2 分钟'],
    [/^(\d+) days (\d+) hours (\d+) min$/, '$1 天 $2 小时 $3 分钟'],
    [/^(\d+) days (\d+) hours (\d+) min (\d+)$/, '$1 天 $2 小时 $3 分钟 $4'],
    [/^(\d+) days (\d+) hours (\d+)$/, '$1 天 $2 小时 $3'],
    [/^(\d+) days (\d+) hour (\d+) min (\d+)$/, '$1 天 $2 小时 $3 分钟 $4'],
    [/^(\d+) day (\d+) hour (\d+) min (\d+)$/, '$1 天 $2 小时 $3 分钟 $4'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);